// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI-powered incident report classifier.
 *
 * This file defines a Genkit flow for classifying incident reports based on their content.
 * The flow uses a language model to categorize reports, enabling administrators to quickly
 * prioritize and assign them to the appropriate personnel. It now supports multimodal input,

 * allowing for text and image analysis.
 *
 * @requires genkit
 * @requires zod
 *
 * @exports classifyIncidentReport - The main function to classify an incident report.
 * @exports ClassifyIncidentReportInput - The input type for the classifyIncidentReport function.
 * @exports ClassifyIncidentReportOutput - The output type for the classifyIncidentReport function.
 */

import { ai } from '@/ai/genkit';
import {z} from 'genkit';

/**
 * Input schema for classifying incident reports.
 */
const ClassifyIncidentReportInputSchema = z.object({
  reportText: z
    .string()
    .describe('The text content of the incident report.'),
  media: z
    .string()
    .optional()
    .describe(
      "Optional media (image) attached to the report, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});

/**
 * Type definition for the input to the classifyIncidentReport function.
 */
export type ClassifyIncidentReportInput = z.infer<
  typeof ClassifyIncidentReportInputSchema
>;

/**
 * Output schema for the classified incident report.
 */
const ClassifyIncidentReportOutputSchema = z.object({
  category: z
    .string()
    .describe(
      'The predicted category of the incident report (e.g., harassment, theft, vandalism).'
    ),
  confidence: z
    .number()
    .describe(
      'A confidence score (0-1) indicating the certainty of the category assignment.'
    ),
  keywords: z
    .array(z.string())
    .describe('Keywords extracted from the incident report text and/or image.'),
});

/**
 * Type definition for the output of the classifyIncidentReport function.
 */
export type ClassifyIncidentReportOutput = z.infer<
  typeof ClassifyIncidentReportOutputSchema
>;

/**
 * Main function to classify an incident report.
 * @param input - The input containing the incident report text and optional media.
 * @returns A promise resolving to the classification result.
 */
export async function classifyIncidentReport(
  input: ClassifyIncidentReportInput
): Promise<ClassifyIncidentReportOutput> {
  return classifyIncidentReportFlow(input);
}

const classifyIncidentReportPrompt = ai.definePrompt({
  name: 'classifyIncidentReportPrompt',
  input: {schema: ClassifyIncidentReportInputSchema},
  output: {schema: ClassifyIncidentReportOutputSchema},
  prompt: `You are an AI assistant that classifies incident reports based on their text content and an optional attached image.

  Analyze the following incident report and determine the most appropriate category, a confidence score (between 0 and 1), and extract relevant keywords from both the text and the image if provided.

  Report Text: {{{reportText}}}
  
  {{#if media}}
  Attached Image: {{media url=media}}
  Analyze the image for context, objects, and actions relevant to the report.
  {{/if}}

  Respond with a JSON object containing the category, confidence score, and keywords.
  `,
});

/**
 * Genkit flow for classifying incident reports.
 */
const classifyIncidentReportFlow = ai.defineFlow(
  {
    name: 'classifyIncidentReportFlow',
    inputSchema: ClassifyIncidentReportInputSchema,
    outputSchema: ClassifyIncidentReportOutputSchema,
  },
  async input => {
    const {output} = await classifyIncidentReportPrompt(input);
    return output!;
  }
);
