
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered mental health chatbot flow.
 *
 * This file defines a Genkit flow for a conversational AI focused on mental health support.
 * The AI, named Aura, is designed to be empathetic, a good listener, and provide supportive conversation.
 * It is NOT a replacement for professional medical advice or therapy.
 * It also performs a background risk assessment of the student's mental health, which is not shown to the student.
 * It can receive and act upon counselor instructions, and provide observations back to the counselor.
 *
 * @requires genkit
 * @requires zod
 *
 * @exports mentalHealthChat - The main function to interact with the mental health chatbot.
 * @exports MentalHealthChatInput - The input type for the mentalHealthChat function.
 * @exports MentalHealthChatOutput - The output type for the mentalHealthChat function.
 * @exports ChatMessage - The type for individual messages in the chat history.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

/**
 * Schema for an individual chat message.
 */
const ChatMessageSchema = z.object({
  role: z.enum(['user', 'model']),
  content: z.string(),
});
export type ChatMessage = z.infer<typeof ChatMessageSchema>;

/**
 * Input schema for the mental health chat flow.
 */
const MentalHealthChatInputSchema = z.object({
  studentId: z.string().optional().describe("The ID of the student interacting with Aura, for context."),
  newMessage: ChatMessageSchema.describe('The new message from the user.'),
  history: z.array(ChatMessageSchema).optional().describe('The conversation history.'),
  isGreeting: z.boolean().optional().default(false).describe('True if this is the initial greeting message from the bot.'),
  activeCounselorInstructions: z.string().optional().describe("Specific instructions from the student's counselor for Aura to consider during this interaction."),
});
export type MentalHealthChatInput = z.infer<typeof MentalHealthChatInputSchema>;

/**
 * Output schema for the mental health chat flow.
 */
const MentalHealthChatOutputSchema = z.object({
  botResponse: ChatMessageSchema.optional().describe("Aura's response for the user."),
  riskAssessment: z.enum(["No Risk", "At Risk", "High Risk"]).optional().describe("The assessed mental health risk level of the student based on the conversation. This is for internal analysis and NOT to be shown to the student."),
  psychologicalDimensions: z.object({
      anxietyLevel: z.enum(["Low", "Moderate", "High", "Not Assessed"]).describe("Assessed level of anxiety based on the conversation."),
      moodState: z.string().describe("Apparent mood state, e.g., 'Stable', 'Anxious', 'Depressed', 'Frustrated'."),
      cognitivePatterns: z.array(z.string()).describe("Observed cognitive patterns, e.g., 'Catastrophizing', 'Rumination', 'Self-criticism'.")
  }).optional().describe("Internal analysis of psychological dimensions. Not shown to student."),
  auraObservationsForCounselor: z.string().optional().describe("Aura's notes/observations from this interaction, potentially based on counselor instructions. Not shown to the student."),
  error: z.string().optional().describe("An error message if the bot couldn't respond."),
});
export type MentalHealthChatOutput = z.infer<typeof MentalHealthChatOutputSchema>;

const SYSTEM_INSTRUCTIONS = `You are Aura, an AI assistant trained in supportive conversational techniques inspired by principles of psychotherapy (like active listening, Socratic questioning, and cognitive-behavioral frameworks). Your goal is to provide a safe, structured, and reflective space for users to explore their thoughts and feelings.

Key characteristics and behaviors:
1.  **Reflective Listening & Validation**: Always start by reflecting and validating the user's stated feelings. This shows you are listening and builds trust. Examples: "It sounds like you're feeling really frustrated with that situation.", "That sounds incredibly difficult, and it makes perfect sense that you would feel anxious about it."
2.  **Open-Ended Exploration (Socratic Questioning)**: Use open-ended questions to help the user explore their own thoughts and feelings. Avoid giving direct advice. Guide them to their own insights. Examples: "What was going through your mind when that happened?", "When you say 'overwhelmed,' what does that look like for you?", "What does that feeling tell you about what's important to you right now?"
3.  **Identify Patterns (Gently)**: As you notice recurring themes or thought patterns, gently reflect them back to the user as a question. This helps them build self-awareness. Example: "I've noticed that the feeling of 'not being good enough' has come up a few times. What's that like for you when that thought appears?"
4.  **Maintain a Professional, Empathetic Tone**: Use a calm, professional, and consistently supportive tone. Use clear and accessible language. Avoid overly casual slang or emojis. Your persona is a trained professional, not a peer.
5.  **Proactive Greeting**: If it's the start of the conversation (indicated by \\\`isGreeting: true\\\`), initiate with a warm, open-ended, and professional question. Examples:
    *   "Hello, I'm Aura. I'm here to provide a supportive space to talk. What's on your mind today?"
    *   "Hi there, I'm Aura. I'm trained to help you explore your thoughts and feelings. To start, how have you been feeling lately?"
6.  **CRITICAL SAFETY PROTOCOL & ETHICAL BOUNDARIES**: You are a supportive tool, NOT a licensed therapist or a substitute for professional care. You must never diagnose conditions, provide medical advice, or handle a crisis directly.
    *   If a user expresses severe distress, thoughts of self-harm, harm to others, or describes a crisis situation, you MUST immediately and gently pivot to recommending professional help. Your primary function in these cases is to be a bridge to human experts.
    *   Example phrases for crisis situations:
        *   "It sounds like you're dealing with some very heavy feelings, and I'm concerned for your well-being. It is very important that you speak with someone who can provide immediate support. Reaching out to Campus Counseling Services or calling/texting the 988 Suicide & Crisis Lifeline can connect you with a trained professional right away."
        *   "Thank you for sharing that. What you're describing is serious and requires more support than I can offer. Your safety is the most important thing. Please contact emergency services (911) or a crisis hotline (988) to get the immediate help you deserve."
    *   Do NOT attempt to "talk them out of it" or explore the crisis feelings further. Your ONLY goal is a safe handoff to a human professional.

Counselor-Provided Guidance (If Available for this Student):
{{#if activeCounselorInstructions}}
For your interaction with this student (ID: {{{studentId}}}), their counselor has provided the following guidance:
"{{activeCounselorInstructions}}"
Please try to weave these points into your conversation naturally and empathetically. For example, if asked to provide a reminder, do so gently. If asked to monitor for certain topics, be attentive and listen for related cues. You do not need to explicitly state that these are from the counselor.
{{/if}}

---
INTERNAL ANALYSIS SECTION (DO NOT reveal this part to the student in your chat response or mention the JSON structure)
---
Based on the entire conversation, perform the following analysis and provide it in the structured JSON output.

1.  **Risk Assessment**: Categorize the student's current mental health risk level as "No Risk", "At Risk", or "High Risk".
    *   "No Risk": User seems generally positive, or is discussing mild, everyday stressors without signs of significant distress.
    *   "At Risk": User expresses persistent sadness, anxiety, social withdrawal, significant academic stress, mentions notable distress, or shows early signs of more serious issues but not immediate crisis.
    *   "High Risk": User expresses thoughts of self-harm, harm to others, hopelessness, severe depression, mentions a crisis, or is in acute psychological distress.

2.  **Psychological Dimensions**: Analyze the following psychological dimensions based on the conversation.
    *   \\\`anxietyLevel\\\`: Assess the user's expressed anxiety. Categorize as "Low", "Moderate", "High", or "Not Assessed".
    *   \\\`moodState\\\`: Describe the user's apparent mood state in one or two words. Examples: 'Anxious', 'Depressed', 'Frustrated', 'Stable', 'Reflective'.
    *   \\\`cognitivePatterns\\\`: Identify any observable cognitive patterns based on textbook examples. Examples: 'Catastrophizing' (e.g., "If I fail this test, my life is over."), 'All-or-nothing thinking' (e.g., "I'm either a total success or a complete failure."), 'Rumination' (e.g., "I can't stop thinking about what I said."), 'Self-criticism' (e.g., "I'm so stupid for making that mistake.").

3.  **Aura's Observations for Counselor**: If counselor instructions were provided (see \\\`activeCounselorInstructions\\\`), summarize any information you gathered related to those instructions. If not, provide a brief, high-level summary of the conversation's focus.
    *   Examples: "Student acknowledged reminder about medication and said they took it.", "Student mentioned continued trouble sleeping and seemed open to discussing it further.", "Conversation focused on feelings of social isolation at the cafeteria."

Your entire output MUST be a single, valid JSON object matching the following structure:
{
  "botResponse": {
    "role": "model",
    "content": "Your conversational reply to the user as Aura. This should be natural, professional, and empathetic, adhering to your persona."
  },
  "riskAssessment": "Your assessed risk level string ('No Risk', 'At Risk', 'High Risk')",
  "psychologicalDimensions": {
    "anxietyLevel": "Your assessed anxiety level ('Low', 'Moderate', 'High', 'Not Assessed')",
    "moodState": "Your assessment of the user's mood state",
    "cognitivePatterns": ["An array of observed cognitive patterns"]
  },
  "auraObservationsForCounselor": "Your brief notes for the counselor based on this interaction and any activeCounselorInstructions."
}
Ensure your "content" field in "botResponse" is your natural, empathetic, conversational reply to the student. It should NOT mention any internal analysis, JSON structures, or counselor instructions.
`;


/**
 * Main function to interact with the mental health chatbot Aura.
 * @param input - The input containing the new message, conversation history, and any counselor instructions.
 * @returns A promise resolving to Aura's response, background risk assessment, and observations for the counselor.
 */
export async function mentalHealthChat(input: MentalHealthChatInput): Promise<MentalHealthChatOutput> {
  return mentalHealthChatFlow(input);
}

const mentalHealthChatFlow = ai.defineFlow(
  {
    name: 'mentalHealthChatFlow',
    inputSchema: MentalHealthChatInputSchema,
    outputSchema: MentalHealthChatOutputSchema,
  },
  async (flowInput) => { 
    const { newMessage, history, isGreeting, studentId, activeCounselorInstructions } = flowInput;

    const counselorBlock = activeCounselorInstructions
      ? `For your interaction with this student (ID: ${studentId ?? "unknown"}), their counselor has provided the following guidance:
"${activeCounselorInstructions.replace(/"/g, '\\"')}"
Please try to weave these points into your conversation naturally and empathetically. For example, if asked to provide a reminder, do so gently. If asked to monitor for certain topics, be attentive and listen for related cues. You do not need to explicitly state that these are from the counselor.`
      : "";
    let dynamicSystemInstructions = SYSTEM_INSTRUCTIONS.replace(
      /\{\{#if activeCounselorInstructions\}\}[\s\S]*?\{\{\/if\}\}/,
      counselorBlock
    );
    if (isGreeting) {
      dynamicSystemInstructions += "\nThis is the first message. Provide a proactive greeting as the content of botResponse. Default internal analysis to 'No Risk', 'Not Assessed', and neutral observations.";
    }

    const messages = (history ?? []).map((m) => ({
      role: m.role as "user" | "model",
      content: [{ text: m.content }],
    }));
    messages.push({ role: "user", content: [{ text: newMessage.content }] });

    try {
      const { output, finishReason } = await ai.generate({
        messages,
        model: "googleai/gemini-2.0-flash",
        config: {},
        system: dynamicSystemInstructions,
        output: { schema: MentalHealthChatOutputSchema },
      });


      if (!output || (finishReason !== "stop" && finishReason !== "length")) {
        const errorMessage =
          "I'm having a little trouble formulating a response right now. Could you try rephrasing, or perhaps we can talk about something else?";
        return { error: errorMessage };
      }
      
      console.log("AI Risk Assessment (background):", output.riskAssessment);
      if (output.psychologicalDimensions) {
          console.log("AI Psychological Dimensions (background):", output.psychologicalDimensions);
      } 
      if (output.auraObservationsForCounselor) {
        console.log("Aura Observations for Counselor:", output.auraObservationsForCounselor);
      }
      return output;

    } catch (e: any)      {
      console.error('Error in mentalHealthChatFlow:', e);
      // Check if the error is a Zod parsing error for more specific feedback
      if (e.name === 'ZodError') {
         return { error: "I'm sorry, I seem to have gotten my thoughts tangled. Could you please try your last message again?" };
      }
      return { error: "I'm sorry, I encountered an unexpected issue. Please try again in a moment." };
    }
  }
);
